# Remote Python Debugger
# https://www.home-assistant.io/integrations/debugpy/
debugpy:

# Logger
# https://www.home-assistant.io/integrations/logger/
logger:
  default: info
  logs:
    custom_components.vita_blackouts: debug
